export interface CalculatorMeta {
  slug: string;
  name: string;
  shortName: string;
  description: string;
  category: "financial" | "math" | "health" | "utility";
  icon: string; // emoji
  color: string; // tailwind gradient from
  colorTo: string; // tailwind gradient to
  keywords: string[];
  searchVolume: string; // for internal reference
}

export const CALCULATORS: Record<string, CalculatorMeta> = {
  "emi": {
    slug: "emi",
    name: "EMI Calculator",
    shortName: "EMI",
    description: "Calculate Equated Monthly Installments for home loan, car loan, or personal loan. See monthly payments, total interest, and full amortization schedule with interactive charts. Free, no signup.",
    category: "financial",
    icon: "🏠",
    color: "from-blue-500",
    colorTo: "to-indigo-600",
    keywords: ["EMI calculator", "loan EMI calculator", "home loan EMI", "car loan EMI", "personal loan EMI", "loan calculator", "home loan calculator", "loan EMI calculator online", "EMI calculator India", "housing loan EMI calculator", "auto loan calculator"],
    searchVolume: "1M+/mo",
  },
  "sip": {
    slug: "sip",
    name: "SIP Calculator",
    shortName: "SIP",
    description: "Calculate returns on Systematic Investment Plan (SIP) in mutual funds. See how your monthly investment grows over 5, 10, 20 years with compound returns and interactive growth charts.",
    category: "financial",
    icon: "📈",
    color: "from-emerald-500",
    colorTo: "to-teal-600",
    keywords: ["SIP calculator", "mutual fund SIP calculator", "SIP returns calculator", "mutual fund calculator", "monthly investment calculator", "SIP investment calculator", "systematic investment plan calculator", "SIP calculator India", "lumpsum vs SIP calculator"],
    searchVolume: "500K/mo",
  },
  "compound-interest": {
    slug: "compound-interest",
    name: "Compound Interest Calculator",
    shortName: "Compound Interest",
    description: "Calculate compound interest with annual, monthly, quarterly, or daily compounding. Visualize investment growth over time with interactive charts. Free compound interest calculator online.",
    category: "financial",
    icon: "💰",
    color: "from-amber-500",
    colorTo: "to-orange-600",
    keywords: ["compound interest calculator", "CI calculator", "interest calculator", "compound interest formula", "compound interest online", "investment growth calculator", "interest rate calculator", "FD interest calculator"],
    searchVolume: "500K/mo",
  },
  "gst": {
    slug: "gst",
    name: "GST Calculator",
    shortName: "GST",
    description: "Calculate GST, VAT, or Sales Tax on any amount. Add or remove tax at any rate. Country-aware: shows GST for India, VAT for UK/EU, Sales Tax for US. Free tax calculator.",
    category: "financial",
    icon: "🧾",
    color: "from-violet-500",
    colorTo: "to-purple-600",
    keywords: ["GST calculator", "GST calculator India", "add GST", "remove GST", "GST calculator online", "CGST SGST calculator", "18% GST calculator", "goods and services tax calculator"],
    searchVolume: "300K/mo",
  },
  "percentage": {
    slug: "percentage",
    name: "Percentage Calculator",
    shortName: "Percentage",
    description: "Calculate percentage of a number, percentage increase/decrease, and what percent one number is of another. Three calculation modes for every percentage question. Free, instant results.",
    category: "math",
    icon: "%",
    color: "from-pink-500",
    colorTo: "to-rose-600",
    keywords: ["percentage calculator", "percent calculator", "percentage increase calculator", "percentage decrease calculator", "percentage change calculator", "what percent is", "calculate percentage online"],
    searchVolume: "500K/mo",
  },
  "bmi": {
    slug: "bmi",
    name: "BMI Calculator",
    shortName: "BMI",
    description: "Calculate your Body Mass Index (BMI) and find out if your weight is healthy. Supports metric (kg/cm) and imperial (lbs/inches). See your BMI category, healthy range, and personalized tips.",
    category: "health",
    icon: "⚖️",
    color: "from-green-500",
    colorTo: "to-emerald-600",
    keywords: ["BMI calculator", "body mass index calculator", "weight calculator", "BMI calculator kg", "BMI calculator lbs", "BMI check online", "healthy weight calculator", "am I overweight calculator", "BMI calculator for men", "BMI calculator for women", "BMI calculator metric", "BMI calculator imperial", "ideal weight for height", "obesity calculator", "underweight calculator", "BMI chart", "BMI range", "normal BMI range"],
    searchVolume: "500K/mo",
  },
  "age": {
    slug: "age",
    name: "Age Calculator",
    shortName: "Age",
    description: "Calculate your exact age in years, months, and days from your date of birth. Find days until your next birthday, age in weeks, and fun milestones. Free online age calculator.",
    category: "utility",
    icon: "🎂",
    color: "from-cyan-500",
    colorTo: "to-blue-600",
    keywords: ["age calculator", "date of birth calculator", "how old am I", "birthday calculator", "age in days calculator", "age in months", "age in weeks", "exact age calculator", "age difference calculator", "chronological age calculator", "days until birthday", "next birthday countdown", "age calculator online free"],
    searchVolume: "300K/mo",
  },
  "mortgage": {
    slug: "mortgage",
    name: "Mortgage Calculator",
    shortName: "Mortgage",
    description: "Calculate monthly mortgage payments, total interest, and see a full amortization schedule. Compare 15-year vs 30-year mortgages. Supports any currency and down payment. Free mortgage calculator.",
    category: "financial",
    icon: "🏡",
    color: "from-sky-500",
    colorTo: "to-blue-600",
    keywords: ["mortgage calculator", "home loan calculator", "housing loan calculator", "mortgage payment calculator", "home loan EMI calculator", "mortgage rate calculator", "house payment calculator", "mortgage amortization calculator", "how much house can I afford", "monthly mortgage payment", "mortgage calculator with down payment", "30 year mortgage calculator", "15 year mortgage calculator", "mortgage interest calculator"],
    searchVolume: "2M+/mo",
  },
  "salary": {
    slug: "salary",
    name: "Salary Calculator",
    shortName: "Salary",
    description: "Convert between hourly, daily, weekly, monthly, and annual salary instantly. See your take-home pay breakdown. Perfect for freelancers, job seekers, and salary negotiations worldwide.",
    category: "financial",
    icon: "💼",
    color: "from-indigo-500",
    colorTo: "to-violet-600",
    keywords: ["salary calculator", "take home pay calculator", "hourly to annual salary", "salary to hourly converter", "annual salary calculator", "monthly salary calculator", "weekly pay calculator", "hourly rate calculator", "pay calculator", "wage calculator", "salary converter", "how much do I make per hour", "income calculator"],
    searchVolume: "300K/mo",
  },
  "discount": {
    slug: "discount",
    name: "Discount Calculator",
    shortName: "Discount",
    description: "Calculate sale price after any percentage discount. See exactly how much you save and the final price you pay. Works for any store, any sale, any currency. Free discount calculator.",
    category: "math",
    icon: "🏷️",
    color: "from-red-500",
    colorTo: "to-pink-600",
    keywords: ["discount calculator", "sale price calculator", "percentage off calculator", "coupon calculator", "how much do I save", "price after discount", "discount percentage calculator", "original price calculator", "markdown calculator", "savings calculator shopping", "what is the sale price"],
    searchVolume: "200K/mo",
  },
  "tip": {
    slug: "tip",
    name: "Tip Calculator",
    shortName: "Tip",
    description: "Calculate tip amount and split the bill between friends at restaurants. See tip for 15%, 18%, 20%, or custom percentage. Per-person breakdown for groups. Free tip calculator.",
    category: "utility",
    icon: "🍽️",
    color: "from-yellow-500",
    colorTo: "to-amber-600",
    keywords: ["tip calculator", "restaurant tip calculator", "bill split calculator", "gratuity calculator", "how much to tip", "tip percentage calculator", "split bill calculator", "dinner tip calculator", "tipping calculator", "how much should I tip", "tip calculator for groups"],
    searchVolume: "200K/mo",
  },
  "fuel": {
    slug: "fuel",
    name: "Fuel Cost Calculator",
    shortName: "Fuel Cost",
    description: "Calculate fuel cost for any trip based on distance, vehicle fuel efficiency, and current fuel price. Plan road trips, estimate daily commute costs, and compare driving vs flying.",
    category: "utility",
    icon: "⛽",
    color: "from-orange-500",
    colorTo: "to-red-600",
    keywords: ["fuel cost calculator", "gas calculator", "mileage calculator", "trip fuel cost", "road trip calculator", "petrol cost calculator", "diesel cost calculator", "fuel consumption calculator", "gas trip calculator", "cost per mile calculator", "cost per km calculator", "fuel efficiency calculator", "how much fuel for trip"],
    searchVolume: "150K/mo",
  },
  "income-tax": {
    slug: "income-tax",
    name: "Income Tax Calculator",
    shortName: "Income Tax",
    description: "Estimate your income tax for India (old/new regime), USA (federal brackets), and UK (PAYE). See your effective rate, bracket breakdown, and take-home pay. Free income tax calculator.",
    category: "financial",
    icon: "📊",
    color: "from-teal-500",
    colorTo: "to-cyan-600",
    keywords: ["income tax calculator", "tax calculator", "income tax calculator India", "income tax calculator USA", "income tax calculator UK", "federal tax calculator", "tax bracket calculator", "tax estimator", "how much tax do I owe", "salary tax calculator", "income tax slab calculator", "new regime tax calculator", "old regime tax calculator", "effective tax rate calculator"],
    searchVolume: "500K/mo",
  },
  "currency": {
    slug: "currency",
    name: "Currency Converter",
    shortName: "Currency",
    description: "Convert between 30+ world currencies with live European Central Bank rates. USD, EUR, GBP, INR, JPY, AED, CAD, AUD, and more. Real-time exchange rate converter, updated daily.",
    category: "financial",
    icon: "💱",
    color: "from-lime-500",
    colorTo: "to-green-600",
    keywords: ["currency converter", "USD to INR", "currency exchange calculator", "EUR to USD", "GBP to INR", "AED to INR", "INR to USD", "dollar to rupee", "pound to rupee", "euro to dollar", "currency exchange rate", "forex calculator", "money converter", "live exchange rate", "ECB exchange rate"],
    searchVolume: "1M+/mo",
  },
  "retirement": {
    slug: "retirement",
    name: "Retirement Calculator",
    shortName: "Retirement",
    description: "Plan your retirement savings and calculate how much to save monthly. Supports 401(k), pension, and FIRE planning. See if your corpus will last through retirement with compare mode.",
    category: "financial",
    icon: "🏖️",
    color: "from-fuchsia-500",
    colorTo: "to-pink-600",
    keywords: ["retirement calculator", "401k calculator", "pension calculator", "retirement savings", "retirement planning calculator", "retirement corpus calculator", "how much to save for retirement", "retirement fund calculator", "early retirement calculator", "retirement age calculator", "when can I retire", "retirement savings goal", "superannuation calculator"],
    searchVolume: "300K/mo",
  },

  // ── NEW Financial Calculators ─────────────────────
  "loan-eligibility": {
    slug: "loan-eligibility",
    name: "Loan Eligibility Calculator",
    shortName: "Loan Eligibility",
    description: "Find out how much loan you can afford based on your income, existing debts, and desired tenure.",
    category: "financial",
    icon: "🏦",
    color: "from-blue-500",
    colorTo: "to-cyan-600",
    keywords: ["loan eligibility calculator", "how much loan can I get", "home loan eligibility", "loan affordability calculator", "maximum loan amount calculator", "loan qualification calculator"],
    searchVolume: "200K/mo",
  },
  "savings-goal": {
    slug: "savings-goal",
    name: "Savings Goal Calculator",
    shortName: "Savings Goal",
    description: "Calculate how long to reach your savings goal or how much to save monthly to hit your target.",
    category: "financial",
    icon: "🎯",
    color: "from-emerald-500",
    colorTo: "to-green-600",
    keywords: ["savings goal calculator", "how long to save", "savings calculator", "monthly savings calculator", "savings target calculator", "how much to save per month"],
    searchVolume: "150K/mo",
  },
  "investment": {
    slug: "investment",
    name: "Investment Calculator",
    shortName: "Investment",
    description: "Calculate how your investment grows over time with initial amount, monthly additions, and compound returns.",
    category: "financial",
    icon: "📊",
    color: "from-violet-500",
    colorTo: "to-indigo-600",
    keywords: ["investment calculator", "investment return calculator", "investment growth calculator", "compound investment calculator", "how much will my investment grow", "investment profit calculator"],
    searchVolume: "300K/mo",
  },
  "inflation": {
    slug: "inflation",
    name: "Inflation Calculator",
    shortName: "Inflation",
    description: "See what your money will be worth in the future and how inflation erodes purchasing power over time.",
    category: "financial",
    icon: "📉",
    color: "from-red-500",
    colorTo: "to-orange-600",
    keywords: ["inflation calculator", "future value calculator", "purchasing power calculator", "inflation rate calculator", "what will my money be worth", "cost of inflation calculator"],
    searchVolume: "200K/mo",
  },
  "cagr": {
    slug: "cagr",
    name: "CAGR Calculator",
    shortName: "CAGR",
    description: "Calculate the Compound Annual Growth Rate of your investment, business revenue, or any value over time.",
    category: "financial",
    icon: "📈",
    color: "from-teal-500",
    colorTo: "to-emerald-600",
    keywords: ["CAGR calculator", "compound annual growth rate", "CAGR formula", "annual growth rate calculator", "investment growth rate calculator", "CAGR calculator online"],
    searchVolume: "150K/mo",
  },
  "break-even": {
    slug: "break-even",
    name: "Break-Even Calculator",
    shortName: "Break-Even",
    description: "Calculate how many units you need to sell to cover your costs. Essential for business planning.",
    category: "financial",
    icon: "⚖️",
    color: "from-amber-500",
    colorTo: "to-yellow-600",
    keywords: ["break even calculator", "break even point calculator", "break even analysis calculator", "business break even", "how many units to sell", "break even formula"],
    searchVolume: "100K/mo",
  },
  "profit-margin": {
    slug: "profit-margin",
    name: "Profit Margin Calculator",
    shortName: "Profit Margin",
    description: "Calculate profit margin percentage, markup, and per-unit profit from revenue and cost figures.",
    category: "financial",
    icon: "💵",
    color: "from-green-500",
    colorTo: "to-emerald-600",
    keywords: ["profit margin calculator", "markup calculator", "profit calculator", "gross margin calculator", "profit margin formula", "margin vs markup calculator"],
    searchVolume: "200K/mo",
  },

  // ── NEW Health Calculators ────────────────────────
  "calorie": {
    slug: "calorie",
    name: "Calorie Calculator",
    shortName: "Calories",
    description: "Calculate your daily calorie needs (TDEE) based on age, gender, weight, height, and activity level.",
    category: "health",
    icon: "🔥",
    color: "from-orange-500",
    colorTo: "to-red-600",
    keywords: ["calorie calculator", "TDEE calculator", "daily calorie calculator", "calorie intake calculator", "how many calories do I need", "BMR calculator", "calorie needs calculator", "maintenance calories calculator"],
    searchVolume: "1M+/mo",
  },
  "pregnancy": {
    slug: "pregnancy",
    name: "Pregnancy Due Date Calculator",
    shortName: "Pregnancy",
    description: "Calculate your estimated due date, current week of pregnancy, and track milestones from your last period date.",
    category: "health",
    icon: "🤰",
    color: "from-pink-500",
    colorTo: "to-purple-600",
    keywords: ["pregnancy calculator", "due date calculator", "pregnancy week calculator", "when is my baby due", "pregnancy due date", "conception date calculator", "how far along am I"],
    searchVolume: "500K/mo",
  },
  "body-fat": {
    slug: "body-fat",
    name: "Body Fat Calculator",
    shortName: "Body Fat",
    description: "Calculate your body fat percentage using the US Navy method. See fat mass, lean mass, and fitness category.",
    category: "health",
    icon: "💪",
    color: "from-cyan-500",
    colorTo: "to-blue-600",
    keywords: ["body fat calculator", "body fat percentage calculator", "body composition calculator", "US Navy body fat calculator", "lean mass calculator", "fat percentage calculator"],
    searchVolume: "300K/mo",
  },
  "water-intake": {
    slug: "water-intake",
    name: "Water Intake Calculator",
    shortName: "Water Intake",
    description: "Calculate how much water you should drink daily based on your weight, activity level, and climate.",
    category: "health",
    icon: "💧",
    color: "from-blue-400",
    colorTo: "to-cyan-500",
    keywords: ["water intake calculator", "how much water should I drink", "daily water intake", "water calculator", "hydration calculator", "water consumption calculator"],
    searchVolume: "200K/mo",
  },
  "heart-rate": {
    slug: "heart-rate",
    name: "Heart Rate Zone Calculator",
    shortName: "Heart Rate",
    description: "Calculate your target heart rate zones for fat burning, cardio, and peak training based on your age.",
    category: "health",
    icon: "❤️",
    color: "from-red-500",
    colorTo: "to-rose-600",
    keywords: ["heart rate zone calculator", "target heart rate calculator", "fat burning heart rate", "cardio zone calculator", "max heart rate calculator", "training zone calculator", "Karvonen calculator"],
    searchVolume: "150K/mo",
  },

  // ── NEW Math/Utility Calculators ──────────────────
  "scientific": {
    slug: "scientific",
    name: "Scientific Calculator",
    shortName: "Scientific",
    description: "Full-featured scientific calculator with trigonometry, logarithms, powers, memory, and keyboard support.",
    category: "math",
    icon: "🔬",
    color: "from-gray-600",
    colorTo: "to-gray-800",
    keywords: ["scientific calculator", "online scientific calculator", "scientific calculator online", "calculator with sin cos tan", "advanced calculator", "math calculator online", "free scientific calculator"],
    searchVolume: "2M+/mo",
  },
  "date": {
    slug: "date",
    name: "Date Calculator",
    shortName: "Date",
    description: "Calculate days between dates, add or subtract days from a date, and find the day number of any year.",
    category: "utility",
    icon: "📅",
    color: "from-indigo-500",
    colorTo: "to-blue-600",
    keywords: ["date calculator", "days between dates", "date difference calculator", "add days to date", "subtract days from date", "how many days until", "date duration calculator"],
    searchVolume: "500K/mo",
  },
  "timezone": {
    slug: "timezone",
    name: "Time Zone Converter",
    shortName: "Time Zone",
    description: "Convert time between any two time zones worldwide. See current time in 6 major cities at a glance.",
    category: "utility",
    icon: "🌍",
    color: "from-sky-500",
    colorTo: "to-indigo-600",
    keywords: ["time zone converter", "timezone converter", "time zone calculator", "world clock converter", "convert time zones", "time difference calculator", "EST to IST", "PST to GMT"],
    searchVolume: "500K/mo",
  },
  "gpa": {
    slug: "gpa",
    name: "GPA Calculator",
    shortName: "GPA",
    description: "Calculate your college GPA from grades and credits. Support for letter grades and percentage-based grading.",
    category: "utility",
    icon: "🎓",
    color: "from-purple-500",
    colorTo: "to-violet-600",
    keywords: ["GPA calculator", "college GPA calculator", "cumulative GPA calculator", "grade point average calculator", "university GPA calculator", "semester GPA calculator", "GPA calculator online"],
    searchVolume: "500K/mo",
  },
  "unit-converter": {
    slug: "unit-converter",
    name: "Unit Converter",
    shortName: "Units",
    description: "Convert between units of length, weight, temperature, speed, area, volume, digital storage, and time.",
    category: "utility",
    icon: "🔄",
    color: "from-lime-500",
    colorTo: "to-green-600",
    keywords: ["unit converter", "unit conversion calculator", "convert units online", "metric to imperial converter", "length converter", "weight converter", "temperature converter", "km to miles", "kg to lbs", "celsius to fahrenheit"],
    searchVolume: "1M+/mo",
  },
};

export const CALCULATOR_LIST = Object.values(CALCULATORS);

export const CATEGORIES = [
  { id: "financial", name: "Financial", icon: "💰", description: "EMI, SIP, tax, mortgage, loan, investment calculators" },
  { id: "math", name: "Math", icon: "🔢", description: "Percentage, discount, scientific, and unit converters" },
  { id: "health", name: "Health", icon: "💚", description: "BMI, calorie, body fat, pregnancy, and wellness calculators" },
  { id: "utility", name: "Utility", icon: "🛠️", description: "Age, tip, fuel, date, GPA, and everyday calculators" },
] as const;
