export interface CalculatorMeta {
  slug: string;
  name: string;
  shortName: string;
  description: string;
  category: "financial" | "math" | "health" | "utility";
  icon: string; // emoji
  color: string; // tailwind gradient from
  colorTo: string; // tailwind gradient to
  keywords: string[];
  searchVolume: string; // for internal reference
}

export const CALCULATORS: Record<string, CalculatorMeta> = {
  "emi": {
    slug: "emi",
    name: "EMI Calculator",
    shortName: "EMI",
    description: "Calculate Equated Monthly Installments for home loan, car loan, or personal loan. See monthly breakdown with charts.",
    category: "financial",
    icon: "🏠",
    color: "from-blue-500",
    colorTo: "to-indigo-600",
    keywords: ["EMI calculator", "loan EMI calculator", "home loan EMI", "car loan EMI", "personal loan EMI"],
    searchVolume: "1M+/mo",
  },
  "sip": {
    slug: "sip",
    name: "SIP Calculator",
    shortName: "SIP",
    description: "Calculate returns on Systematic Investment Plan (SIP) in mutual funds. See how your money grows over time.",
    category: "financial",
    icon: "📈",
    color: "from-emerald-500",
    colorTo: "to-teal-600",
    keywords: ["SIP calculator", "mutual fund SIP calculator", "SIP returns calculator"],
    searchVolume: "500K/mo",
  },
  "compound-interest": {
    slug: "compound-interest",
    name: "Compound Interest Calculator",
    shortName: "Compound Interest",
    description: "Calculate compound interest with annual, monthly, or daily compounding. Visualize your investment growth.",
    category: "financial",
    icon: "💰",
    color: "from-amber-500",
    colorTo: "to-orange-600",
    keywords: ["compound interest calculator", "CI calculator", "interest calculator"],
    searchVolume: "500K/mo",
  },
  "gst": {
    slug: "gst",
    name: "GST Calculator",
    shortName: "GST",
    description: "Calculate GST amount and total price. Add or remove GST at 5%, 12%, 18%, or 28% rates.",
    category: "financial",
    icon: "🧾",
    color: "from-violet-500",
    colorTo: "to-purple-600",
    keywords: ["GST calculator", "GST calculator India", "add GST", "remove GST"],
    searchVolume: "300K/mo",
  },
  "percentage": {
    slug: "percentage",
    name: "Percentage Calculator",
    shortName: "Percentage",
    description: "Calculate percentage of a number, percentage increase/decrease, and what percent one number is of another.",
    category: "math",
    icon: "%",
    color: "from-pink-500",
    colorTo: "to-rose-600",
    keywords: ["percentage calculator", "percent calculator", "percentage increase calculator"],
    searchVolume: "500K/mo",
  },
  "bmi": {
    slug: "bmi",
    name: "BMI Calculator",
    shortName: "BMI",
    description: "Calculate your Body Mass Index (BMI) and find out if your weight is healthy for your height.",
    category: "health",
    icon: "⚖️",
    color: "from-green-500",
    colorTo: "to-emerald-600",
    keywords: ["BMI calculator", "body mass index calculator", "weight calculator"],
    searchVolume: "500K/mo",
  },
  "age": {
    slug: "age",
    name: "Age Calculator",
    shortName: "Age",
    description: "Calculate your exact age in years, months, and days. Find days until your next birthday.",
    category: "utility",
    icon: "🎂",
    color: "from-cyan-500",
    colorTo: "to-blue-600",
    keywords: ["age calculator", "date of birth calculator", "how old am I"],
    searchVolume: "300K/mo",
  },
  "mortgage": {
    slug: "mortgage",
    name: "Mortgage Calculator",
    shortName: "Mortgage",
    description: "Calculate monthly mortgage payments, total interest, and see a full amortization schedule for your home loan.",
    category: "financial",
    icon: "🏡",
    color: "from-sky-500",
    colorTo: "to-blue-600",
    keywords: ["mortgage calculator", "home loan calculator", "housing loan calculator"],
    searchVolume: "2M+/mo",
  },
  "salary": {
    slug: "salary",
    name: "Salary Calculator",
    shortName: "Salary",
    description: "Convert between hourly, daily, weekly, monthly, and annual salary. Calculate take-home pay after taxes.",
    category: "financial",
    icon: "💼",
    color: "from-indigo-500",
    colorTo: "to-violet-600",
    keywords: ["salary calculator", "take home pay calculator", "hourly to annual salary"],
    searchVolume: "300K/mo",
  },
  "discount": {
    slug: "discount",
    name: "Discount Calculator",
    shortName: "Discount",
    description: "Calculate sale price after discount. Find how much you save with percentage or flat discounts.",
    category: "math",
    icon: "🏷️",
    color: "from-red-500",
    colorTo: "to-pink-600",
    keywords: ["discount calculator", "sale price calculator", "percentage off calculator"],
    searchVolume: "200K/mo",
  },
  "tip": {
    slug: "tip",
    name: "Tip Calculator",
    shortName: "Tip",
    description: "Calculate tip amount and split the bill between friends. Quick and easy for restaurants.",
    category: "utility",
    icon: "🍽️",
    color: "from-yellow-500",
    colorTo: "to-amber-600",
    keywords: ["tip calculator", "restaurant tip calculator", "bill split calculator"],
    searchVolume: "200K/mo",
  },
  "fuel": {
    slug: "fuel",
    name: "Fuel Cost Calculator",
    shortName: "Fuel Cost",
    description: "Calculate fuel cost for a trip based on distance, fuel efficiency, and fuel price.",
    category: "utility",
    icon: "⛽",
    color: "from-orange-500",
    colorTo: "to-red-600",
    keywords: ["fuel cost calculator", "gas calculator", "mileage calculator", "trip fuel cost"],
    searchVolume: "150K/mo",
  },
  "income-tax": {
    slug: "income-tax",
    name: "Income Tax Calculator",
    shortName: "Income Tax",
    description: "Estimate your income tax liability based on your salary, deductions, and tax regime. Supports India, US, UK.",
    category: "financial",
    icon: "📊",
    color: "from-teal-500",
    colorTo: "to-cyan-600",
    keywords: ["income tax calculator", "tax calculator", "income tax calculator India"],
    searchVolume: "500K/mo",
  },
  "currency": {
    slug: "currency",
    name: "Currency Converter",
    shortName: "Currency",
    description: "Convert between 30+ world currencies with live-ish rates. USD, EUR, GBP, INR, AED, and more.",
    category: "financial",
    icon: "💱",
    color: "from-lime-500",
    colorTo: "to-green-600",
    keywords: ["currency converter", "USD to INR", "currency exchange calculator"],
    searchVolume: "1M+/mo",
  },
  "retirement": {
    slug: "retirement",
    name: "Retirement Calculator",
    shortName: "Retirement",
    description: "Plan your retirement savings. Calculate how much you need to save monthly to reach your retirement goal.",
    category: "financial",
    icon: "🏖️",
    color: "from-fuchsia-500",
    colorTo: "to-pink-600",
    keywords: ["retirement calculator", "401k calculator", "pension calculator", "retirement savings"],
    searchVolume: "300K/mo",
  },
};

export const CALCULATOR_LIST = Object.values(CALCULATORS);

export const CATEGORIES = [
  { id: "financial", name: "Financial", icon: "💰", description: "EMI, SIP, tax, mortgage, salary calculators" },
  { id: "math", name: "Math", icon: "🔢", description: "Percentage, discount, and number calculators" },
  { id: "health", name: "Health", icon: "💚", description: "BMI, calorie, and wellness calculators" },
  { id: "utility", name: "Utility", icon: "🛠️", description: "Age, tip, fuel, and everyday calculators" },
] as const;
